##ResultsFolder = 'C:\\Users\\MasahiroSakurai\\Documents\\SmashStuff'      # Make sure to have double backslashes file paths.
    # ResultsFolder may be left undefined if result .txt files are in the same place as the Python code
DefaultTitleMin = 2
DefaultSort = 'Low'
DefaultSortTie = 'Middle'
DefaultLines = 2
RoundLen = 0             # How many Digits to round to in ranking displays
Rounding = '.' + str(RoundLen) + 'f'
DefaultRating = 1500
DefaultRD = 350
DefaultVol = 0.06
VarianceCutoff = 80      # Only display players with variance of this number or less


# Tags and names go here. There should only be one tag per real name.

TagDict = {}


# Don't touch this.

NameDict = {}
for Tag in TagDict:
    NameDict[TagDict[Tag]] = Tag

    
# Any tags with numbers in them should go here, with the actual tag, then the tag with numbers written out.
# Note that tags of the form A1 or AA1 (that is, a capital letter followed by a number or two capital letters
# followed by a number) do not always process properly, and additional coding may be needing to avoid errors.

NumFixes = []


# Typos, full last names, changed tags, names that have tags, extra spaces, etc., go here.

ReplacementList = [
    ("Oxy.2Jar", "2Jar"),
    ("4 %", "4%"),
    ("4%.", "4%"),
    ("￼Adpextwindong", "Adpextwindong"),
    ('ARC', 'Arc'),
    ('Rmada', 'Armada'),
    ('P4K EMP Armada', 'Armada'),
    ('A_Rookie', 'A Rookie'),
    ('Mortality_Axe', 'Axe'),
    ('Mortality.Axe', 'Axe'),
    ('Mortality Axe', 'Axe'),
    ('Tempostorm Axe', 'Axe'),
    ('Tempo-Axe', 'Axe'),
    ('Tempo.Axe', 'Axe'),
    ('Baka', 'Baka4Moe'),
    ('B4M', 'Baka4Moe'),
    ('Entities From The Beyond Within Corpses Obsessed', 'Bart'),
    ('Bernaldoe', 'Bernal'),
    ('62Bit Bladewise', 'Bladewise'),
    ('Bizarro Flame', 'Bizzarro Flame'),
    ('Bizarroflame', 'Bizzarro Flame'),
    ('Boback Vakili', 'Boback'),
    ('Cactaur', 'Cactuar'),
    ('(Tmg) Captain Faceroll', 'Captain Faceroll'),
    ('Smuckers', 'Captain Smuckers'),
    ("Chillin", 'Chillindude'),
    ('Chillindude829', 'Chillindude'),
    ("Liquid' Chillindude", 'Chillindude'),
    ('Liquid`Chillin', 'Chillindude'),
    ('Chudat', 'Chu Dat'),
    ('Emg_Coastward', 'Coastward'),
    ('(Tmg) Connor', 'Connorthekid'),
    ('Connor', 'Connorthekid'),
    ('(Tmg) Coolkid', 'Coolkid'),
    ('4K.Corkus', 'Corkus'),
    ('Dandy?', 'Dandy'),
    ('Emp Dandy', 'Dandy'),
    ('(Tmg) Dantefox', 'Dantefox'),
    ('Dart', 'Dart!'),
    ('Oxy Dendypretendy', 'Dendypretendy'),
    ('Drugged Fox', 'Druggedfox'),
    ('Druggedfox11', 'Druggedfox'),
    ('XTR Eddy Mexico', 'Eddy Mexico'),
    ('Eddymexico', 'Eddy Mexico'),
    ('Salazar Slitherin (Eggz)', 'Eggz'),
    ('Eikelmann', 'Eikelmannrus'),
    ('Espr Eval', 'Eval'),
    ('Excel_Zero', 'Excel Zero'),
    ('Excelzero', 'Excel Zero'),
    ('Fat Goku', 'Fatgoku'),
    ('CaCAW Slurrpy Snake 32+37 Master', 'Gage'),
    ('EE Gahtzu', 'Gahtzu'),
    ('GK Gahtzu', 'Gahtzu'),
    ('VGBC Hax', 'Hax'),
    ('Frq.Hugs', 'Hugs'),
    ('Liquid`Hungrybox', 'Hungrybox'),
    ('Crs. Hungrybox', 'Hungrybox'),
    ('CRS.Hungrybox', 'Hungrybox'),
    ('Liquid` Hungrybox', 'Hungrybox'),
    ('Liquid Hungrybox', 'Hungrybox'),
    ('Emg_Idea', 'Idea'),
    ('Emg Idea', 'Idea'),
    ('Oxy L J666', 'J666'),
    ('Lll. Jeapie', 'Jeapie'),
    ('CEOJebailey', 'Jebailey'),
    ('Jpeg', 'Jpegimage'),
    ('Kage The Warrior', 'Kage'),
    ('Emg Kirbykaze', 'Kirbykaze'),
    ('LiquidKen', 'Ken'),
    ('Liquid Ken', 'Ken'),
    ("Liquid' Ken", 'Ken'),
    ("Liquid ' Ken", 'Ken'),
    ("Liquid`Ken", 'Ken'),
    ('Skt T1 Talon God (Kira)', 'Kira'),
    ('KDJ', 'Koreandj'),
    ('Liquid`KDJ', 'Koreandj'),
    ('The Pleaup (Kyu Puff)', 'Kyu Puff'),
    ('Beer Man', 'Lambchops'),
    ('Dehf', 'Larry Lurr'),
    ('Laundandus', 'Laudandus'),
    ('Lauduandus', 'Laudandus'),
    ('Laduandus', 'Laudandus'),
    ('Tsm Leffen', 'Leffen'),
    ('MVG Medz', 'Medz'),
    ('C9 MaNg0', 'Mang0'),
    ('C9 Mang0', 'Mang0'),
    ('C9 Mango', 'Mang0'),
    ('C9. Mango', 'Mang0'),
    ('C9.Mango', 'Mang0'),
    ('Mango', 'Mang0'),
    ('Cloud9.Mango', 'Mang0'),
    ('COG MVG mew2king', 'Mew2King'),
    ('PL MVG mew2king', 'Mew2King'),
    ('PL MVG EMP Mew2King', 'Mew2King'),
    ('P4K EMP Mew2King', 'Mew2King'),
    ('P4K Mew2King', 'Mew2King'),
    ('EMP Mew2King', 'Mew2King'),
    ('M2K', 'Mew2King'),
    ('Mvg Mew2King', 'Mew2King'),
    ('Mikehaggarkj', 'Mikehaggar'),
    ('Mike Haggar', 'Mikehaggar'),
    ('Mikehaggarssbm', 'Mikehaggar'),
    ('Mikehaze', 'Mike Haze'),
    ("Jj'S Mikehaze", 'Mike Haze'),
    ("Oes Milkman", 'Milkman'),
    ('HF Neon', 'Neon'),
    ('Vgz Nintendude', 'Nintendude'),
    ('Vgz.Nintendude', 'Nintendude'),
    ('Joey Cheung', 'Ny Joey'),
    ('Secret.Orly', 'Orly'),
    ('Pbj', 'Pb&J'),
    ('P.C. Chris', 'Pc Chris'),
    ('Clg.Pewpewu', 'Pewpewu'),
    ('Clg.Pewpewu Cookiecat', 'Pewpewu'),
    ('Dr. PP', 'PPMD'),
    ('VS Porkchops', 'Porkchops'),
    ('Pokchops', 'Porkchops'),
    ('Esi. Gg Prince Abu', 'Prince Abu'),
    ('Vws Professor Pro', 'Professor Pro'),
    ('Logan', 'Purpletuce'),
    ('LP.raynEX', 'Raynex'),
    ('Lp_Raynex', 'Raynex'),
    ('Lp Raynex', 'Raynex'),
    ('GK Reno', 'Reno'),
    ('Kana Manami', 'Riddlebox'),
    ('Unknown522', 'Ryan Ford'),
    ('(Tmg) Sacasumoto', 'Sacasumoto'),
    ('Emg Sauc3', 'Sauc3'),
    ('Einstein Lover (Sfat)', 'Sfat'),
    ('(Tmg) Sherigami', 'Sherigami'),
    ('Sherigam', 'Sherigami'),
    ('MMG_Shroomed', 'Shroomed'),
    ('Gc Silentwolf', 'Silent Wolf'),
    ('Psg Sk92', 'Sk92'),
    ("Tony'S Hawk (Slox)", 'Slox'),
    ('Smahg0D', 'Smashg0D'),
    ('Smilez =)', 'Smilez :)'),
    ('Smilez=)', 'Smilez :)'),
    ('Smilez', 'Smilez :)'),
    ('Smilez:)', 'Smilez :)'),
    ('Dumb Cunt', 'Smokey'),
    ('Soft', 'S0Ft'),
    ('Soft', 'S0Ft'),
    ('(Tmg) Squid', 'Squid'),
    ('Matt', 'Stab'),
    ('Matt R', 'Stab'),
    ('Stabbedbyanipple', 'Stab'),
    ('Stabbedbyahippie', 'Stab'),
    ('Victor Abdul Latif', 'Stab'),
    ('Victor Abdul Latif (Stab)', 'Stab'),
    ('Viktor Abdul Latif (Stab)', 'Stab'),
    ('(Tmg) Victor Abdul Latif', 'Stab'),
    ('Straight (Second Wave)', 'Straight'),
    ('OXY SUNG475', 'Sung475'),
    ('Oxy_Sung475', 'Sung475'),
    ('James Liu', 'Swedish Delight'),
    ('Swedishdelight', 'Swedish Delight'),
    ('MVG Tai', 'Tai'),
    ('Thegrimereaper', 'Thegrimreaper'),
    ('Trail.', 'Trail'),
    ('Lp_Trulliam', 'Trulliam'),
    ('Lp Trulliam', 'Trulliam'),
    ('TheMoon', 'The Moon'),
    ('Tuxedomask', 'Tuxedo Mask'),
    ('Twin_A', 'Twin A'),
    ('Velovity', 'Velocity'),
    ('Emg Weon-X', 'Weon-X'),
    ('Emg_Weon-X', 'Weon-X'),
    ('Little Boy Big Dreams', 'Weon-X'),
    ('The Ghost of White Marth', 'Weon-X'),
    ('Tempo Westballz', "Westballz"),
    ('CT Wizzrobe', 'Wizzrobe'),
    ('FX_DFW Wobbles', 'Wobbles'),
    ('FX DFW Wobbles', 'Wobbles'),
    ('CT Zero', 'Zero'),
]
